# Generated by Django 5.2.4 on 2025-07-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodrev_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image',
            new_name='photo',
        ),
    ]
