# Generated by Django 5.2.4 on 2025-07-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodrev_app', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='photo',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rev_images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prodrev_app.reviews')),
            ],
        ),
    ]
