# Generated by Django 5.2.4 on 2025-07-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodrev_app', '0005_remove_reviews_photo_reviewimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
